# Generated by Django 2.2.7 on 2020-01-13 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('year_of_birth', models.IntegerField()),
                ('gender', models.CharField(choices=[('w', 'Woman'), ('m', 'Man'), ('d', 'Divers')], max_length=1, null=True)),
                ('ssn', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('le', 'lecture'), ('ex', 'exercise'), ('xx', 'exam')], max_length=2)),
                ('professor', models.ManyToManyField(blank=True, to='yamod.Professor')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yamod.University')),
            ],
        ),
    ]
